#!/usr/bin/env python3
"""Stamp every production config from deploy/production.env.

One source of truth (your domain + cards) drives:

  webapp/public/config.js   API URL, cards, telegram, price  (public, by design)
  server_vps/Caddyfile      the API hostname Caddy gets a cert for
  deploy/vps-env.generated  the env lines to MERGE into /etc/carapk/activation.env

Safety: this never writes your live signing key or Telegram token. Those stay on
the VPS untouched; the generated env file carries only the new/derived values and
says so, so a careless copy cannot clobber the key that mints activations.

Usage:
    cp deploy/production.env.example deploy/production.env
    nano deploy/production.env
    python deploy/configure.py
"""
from __future__ import annotations
import pathlib
import re
import secrets
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV = ROOT / "deploy" / "production.env"


def read_env(path: pathlib.Path) -> dict[str, str]:
    if not path.exists():
        sys.exit(f"missing {path.relative_to(ROOT)}\n"
                 f"  cp deploy/production.env.example deploy/production.env")
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def require(env: dict[str, str], key: str, why: str) -> str:
    v = env.get(key, "").strip()
    if not v:
        sys.exit(f"{key} is empty in deploy/production.env — {why}")
    return v


def js_str(s: str) -> str:
    """Quote for JS, escaping backslashes, quotes and newlines."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def main() -> None:
    env = read_env(ENV)

    domain = require(env, "DOMAIN", "the whole deployment keys off it").lstrip("https://").strip("/")
    if domain == "example.com":
        sys.exit("DOMAIN is still example.com — put your real domain in deploy/production.env")

    app_host = env.get("APP_HOST") or domain
    api_host = env.get("API_HOST") or f"api.{domain}"
    payload_host = env.get("PAYLOAD_HOST") or f"payload.{domain}"

    cards = []
    for n in (1, 2):
        number = env.get(f"CARD_{n}_NUMBER", "").strip()
        if not number:
            continue
        cards.append({
            "brand": env.get(f"CARD_{n}_BRAND", "").strip() or f"CARD {n}",
            "number": number,
            "holder": env.get(f"CARD_{n}_HOLDER", "").strip(),
        })
    if not cards:
        sys.exit("no cards filled in — buyers would have nothing to pay to "
                 "(set CARD_1_NUMBER / CARD_1_HOLDER)")

    telegram = require(env, "TELEGRAM", "buyers need somewhere to send the code")
    price = require(env, "PRICE_TEXT", "the cheque would print nothing")

    # secrets: reuse what's in production.env, else mint strong ones
    hmac_key = env.get("DOWNLOAD_HMAC_KEY") or secrets.token_urlsafe(48)
    payload_secret = env.get("PAYLOAD_AUTH_VALUE") or secrets.token_urlsafe(32)

    # --- webapp/public/config.js -------------------------------------------
    card_lines = ",\n".join(
        f"      {{ brand: {js_str(c['brand'])}, number: {js_str(c['number'])}, "
        f"holder: {js_str(c['holder'])} }}" for c in cards
    )
    config_js = f'''// Public config for the web client. Nothing here is secret — it is served to
// every visitor. The recipe and payload URLs are NOT here; the server issues
// those per approved session.
//
// GENERATED by deploy/configure.py from deploy/production.env.
// Edit that file and re-run, or edit this one directly after deploy (it is
// copied verbatim into dist/, never bundled, so a hand edit survives).
window.CARAPK = {{
  // Activation backend (same one the desktop app uses).
  API: {js_str("https://" + api_host)},

  // Shown on the payment step — your own cards for receiving money.
  PAYMENT: {{
    cards: [
{card_lines},
    ],
  }},
  CONTACTS: {{
    telegram: {js_str(telegram)},
  }},
  PRICE_TEXT: {js_str(price)},

  // Local relay for WIRELESS cars (FAW B70). The agent binds here.
  // USB cars (Dongfeng MAGE) use WebUSB and ignore this.
  RELAY: "ws://127.0.0.1:8765",
}};
'''
    cfg_path = ROOT / "webapp" / "public" / "config.js"
    cfg_path.write_text(config_js)

    # --- server_vps/Caddyfile ----------------------------------------------
    caddy = f'''# /etc/caddy/Caddyfile — auto-HTTPS reverse proxy in front of the API.
# GENERATED by deploy/configure.py.
#
# IMPORTANT: leave {api_host} on "DNS only" (grey cloud) in Cloudflare.
# Behind the orange cloud, Caddy's HTTP-01 challenge cannot complete and cert
# issuance fails. Grey cloud keeps this file working as-is.

{api_host} {{
    reverse_proxy 127.0.0.1:8080
}}
'''
    (ROOT / "server_vps" / "Caddyfile").write_text(caddy)

    # --- deploy/vps-env.generated ------------------------------------------
    vps_env = f'''# Generated by deploy/configure.py — MERGE these lines into
#   /etc/carapk/activation.env      (chmod 600, owned by carapk)
#
# Do NOT replace that whole file: it already holds SIGNING_KEY_PKCS8,
# TG_BOT_TOKEN and TG_CHAT_ID, which must stay exactly as they are. Losing the
# signing key invalidates every activation you have ever issued.

# Browser origins allowed to call the API. Without this the web client dies on
# the CORS preflight with "Load failed".
WEB_ORIGINS=https://{app_host}

# Payload delivery: the browser only ever sees expiring /dl links.
PAYLOAD_ORIGIN=https://{payload_host}
DOWNLOAD_HMAC_KEY={hmac_key}
DOWNLOAD_TTL=900

# The secret header the VPS sends when fetching from PAYLOAD_ORIGIN. Create a
# matching Cloudflare WAF rule on {payload_host}:
#   (http.request.headers["x-payload-auth"][0] ne "{payload_secret}")  ->  Block
PAYLOAD_AUTH=X-Payload-Auth: {payload_secret}
'''
    gen = ROOT / "deploy" / "vps-env.generated"
    gen.write_text(vps_env)
    gen.chmod(0o600)

    # --- summary ------------------------------------------------------------
    vps_ip = env.get("VPS_IP", "").strip() or "<your VPS IP>"
    print(f"""configured for {domain}

  web app      https://{app_host}       (Cloudflare Pages)
  API          https://{api_host}       (VPS, DNS-only / grey cloud)
  payload      https://{payload_host}   (R2 custom domain, header-gated)

wrote:
  webapp/public/config.js      {len(cards)} card(s), price "{price}"
  server_vps/Caddyfile         host {api_host}
  deploy/vps-env.generated     merge into /etc/carapk/activation.env (chmod 600)

Cloudflare DNS to create:
  A     {api_host.split('.')[0]:<10} {vps_ip:<16} DNS only (grey cloud)  <- required for Caddy's cert

next:
  cd webapp && npm run build && npm run preflight
  npx wrangler pages deploy dist --project-name carapk
  # then on the VPS: merge deploy/vps-env.generated, restart the service

full runbook: docs/DEPLOY.md""")


if __name__ == "__main__":
    main()
